export { default as TableSampleStandard } from './TableSampleStandard.vue'
export { default as TableSampleNoPagination  } from './TableSampleNoPagination.vue'
export { default as TableSampleNoMounted  } from './TableSampleNoMounted.vue'
export { default as TableSampleCustomerResponse  } from './TableSampleCustomerResponse.vue'
export { default as TableSampleDynamicDataResolver  } from './TableSampleDynamicDataResolver.vue'